## All characters sprites goes into this file

image lilly_shizu_showdown = "event/lilly_shizu_showdown.jpg"
image saki_canon_big = "event/YKxIzXe-transformed.jpg"
image saki_canon = "event/saki_canon.jpg"
image saki_firework = "event/saki_firework.jpeg"

# Chisato sprites
image chisato basic = "sprites/chisato/chisato_final.png"

# Saki sprites
image saki basic_smile = "sprites/saki/saki_test.png"

# Lilly sprites
image lilly basic_ara = "sprites/lilly/lilly_basic_ara.png"
image lilly basic_cheerful = "sprites/lilly/lilly_basic_cheerful.png"
image lilly basic_concerned = "sprites/lilly/lilly_basic_concerned.png"
image lilly basic_displeased = "sprites/lilly/lilly_basic_displeased.png"
image lilly basic_emb = "sprites/lilly/lilly_basic_emb.png"
image lilly basic_giggle = "sprites/lilly/lilly_basic_giggle.png"
image lilly basic_listen = "sprites/lilly/lilly_basic_listen.png"
image lilly basic_oops = "sprites/lilly/lilly_basic_oops.png"
image lilly basic_surprised = "sprites/lilly/lilly_basic_surprised.png"
image lilly basic_weaksmile = "sprites/lilly/lilly_basic_weaksmile.png"
image lilly basic_planned = "sprites/lilly/lilly_basic_planned.png"
image lilly basic_smileclosed = "sprites/lilly/lilly_basic_smileclosed.png"
image lilly basic_pout = "sprites/lilly/lilly_basic_pout.png"
image lilly basic_smile = "sprites/lilly/lilly_basic_smile.png"
image lilly basic_sleepy = "sprites/lilly/lilly_basic_sleepy.png"
image lilly basic_sad = "sprites/lilly/lilly_basic_sad.png"
image lilly basic_reminisce = "sprites/lilly/lilly_basic_reminisce.png"

# Emi sprites
image emi nude_wink = "sprites/eminude/eminude_wink.png"
image emi nude_weaksmile = "sprites/eminude/eminude_weaksmile.png"
image emi nude_pout = "sprites/eminude/eminude_pout.png"
image emi nude_neutral = "sprites/eminude/eminude_neutral.png"
image emi nude_happy = "sprites/eminude/eminude_happy.png"
image emi nude_grin = "sprites/eminude/eminude_grin.png"
image emi nude_frown = "sprites/eminude/eminude_frown.png"
image emi nude_evil = "sprites/eminude/eminude_evil.png"
image emi nude_closedsmile = "sprites/eminude/eminude_closedsmile.png"
image emi nude_blush = "sprites/eminude/eminude_blush.png"
image emi nude_awayfrown = "sprites/eminude/eminude_awayfrown.png"

image emi cas_wink = "sprites/emicas/emicas_wink.png"
image emi cas_wink_up = "sprites/emicas/emicas_wink_up.png"
image emi cas_weaksmile = "sprites/emicas/emicas_weaksmile.png"
image emi cas_weaksmile_up = "sprites/emicas/emicas_weaksmile_up.png"
image emi cas_smile = "sprites/emicas/emicas_smile.png"
image emi cas_smile_up = "sprites/emicas/emicas_smile_up.png"
image emi cas_sad = "sprites/emicas/emicas_sad.png"
image emi cas_sad_up = "sprites/emicas/emicas_sad_up.png"
image emi cas_pout = "sprites/emicas/emicas_pout.png"
image emi cas_pout_up = "sprites/emicas/emicas_pout_up.png"
image emi cas_neutral = "sprites/emicas/emicas_neutral.png"
image emi cas_neutral_up = "sprites/emicas/emicas_neutral_up.png"
image emi cas_happy = "sprites/emicas/emicas_happy.png"
image emi cas_happy_up = "sprites/emicas/emicas_happy_up.png"
image emi cas_grit = "sprites/emicas/emicas_grit.png"
image emi cas_grin = "sprites/emicas/emicas_grin.png"
image emi cas_grin_up = "sprites/emicas/emicas_grin_up.png"
image emi cas_frown = "sprites/emicas/emicas_frown.png"
image emi cas_frown_up = "sprites/emicas/emicas_frown_up.png"
image emi cas_evil = "sprites/emicas/emicas_evil.png"
image emi cas_closedsmile = "sprites/emicas/emicas_closedsmile.png"
image emi cas_closedsmile_up = "sprites/emicas/emicas_closedsmile_up.png"
image emi cas_blush = "sprites/emicas/emicas_blush.png"
image emi cas_awayfrown = "sprites/emicas/emicas_awayfrown.png"
image emi cas_awayfrown_up = "sprites/emicas/emicas_awayfrown_up.png"
image emi cas_angry = "sprites/emicas/emicas_angry.png"
image emi cas_angry_up = "sprites/emicas/emicas_angry_up.png"

image emi cas_wink_close = "sprites/emicas/close/emicas_wink_close.png"
image emi cas_wink_up_close = "sprites/emicas/close/emicas_wink_up_close.png"
image emi cas_weaksmile_close = "sprites/emicas/close/emicas_weaksmile_close.png"
image emi cas_weaksmile_up_close = "sprites/emicas/close/emicas_weaksmile_up_close.png"
image emi cas_smile_close = "sprites/emicas/close/emicas_smile_close.png"
image emi cas_smile_up_close = "sprites/emicas/close/emicas_smile_up_close.png"
image emi cas_sad_close = "sprites/emicas/close/emicas_sad_close.png"
image emi cas_sad_up_close = "sprites/emicas/close/emicas_sad_up_close.png"
image emi cas_pout_close = "sprites/emicas/close/emicas_pout_close.png"
image emi cas_pout_up_close = "sprites/emicas/close/emicas_pout_up_close.png"
image emi cas_neutral_close = "sprites/emicas/close/emicas_neutral_close.png"
image emi cas_neutral_up_close = "sprites/emicas/close/emicas_neutral_up_close.png"
image emi cas_happy_close = "sprites/emicas/close/emicas_happy_close.png"
image emi cas_happy_up_close = "sprites/emicas/close/emicas_happy_up_close.png"
image emi cas_grit_close = "sprites/emicas/close/emicas_grit_close.png"
image emi cas_grin_close = "sprites/emicas/close/emicas_grin_close.png"
image emi cas_grin_up_close = "sprites/emicas/close/emicas_grin_up_close.png"
image emi cas_frown_close = "sprites/emicas/close/emicas_frown_close.png"
image emi cas_frown_up_close = "sprites/emicas/close/emicas_frown_up_close.png"
image emi cas_evil_close = "sprites/emicas/close/emicas_evil_close.png"
image emi cas_closedsmile_close = "sprites/emicas/close/emicas_closedsmile_close.png"
image emi cas_closedsmile_up_close = "sprites/emicas/close/emicas_closedsmile_up_close.png"
image emi cas_blush_close = "sprites/emicas/close/emicas_blush_close.png"
image emi cas_awayfrown_close = "sprites/emicas/close/emicas_awayfrown_close.png"
image emi cas_awayfrown_up_close = "sprites/emicas/close/emicas_awayfrown_up_close.png"
image emi cas_angry_close = "sprites/emicas/close/emicas_angry_close.png"
image emi cas_angry_up_close = "sprites/emicas/close/emicas_angry_up_close.png"

image emi sad_shyblush_gym_close = "sprites/emi/close/emi_sad_shyblush_gym_close.png"
image emi sad_shy_gym_close = "sprites/emi/close/emi_sad_shy_gym_close.png"
image emi sad_pout_gym_close = "sprites/emi/close/emi_sad_pout_gym_close.png"
image emi sad_grin_gym_close = "sprites/emi/close/emi_sad_grin_gym_close.png"
image emi sad_depressed_gym_close = "sprites/emi/close/emi_sad_depressed_gym_close.png"
image emi sad_annoyed_gym_close = "sprites/emi/close/emi_sad_annoyed_gym_close.png"
image emi emi_sad_angry_gym_close = "sprites/emi/close/emi_sad_angry_gym_close.png"
image emi excited_sad_gym_close = "sprites/emi/close/emi_excited_sad_gym_close.png"
image emi excited_proud_gym_close = "sprites/emi/close/emi_excited_proud_gym_close.png"
image emi excited_laugh_gym_close = "sprites/emi/close/emi_excited_laugh_gym_close.png"
image emi excited_happy_gym_close = "sprites/emi/close/emi_excited_happy_gym_close.png"
image emi excited_amused_gym_close = "sprites/emi/close/emi_excited_amused_gym_close.png"
image emi basic_shock_gym_close = "sprites/emi/close/emi_basic_shock_gym_close.png"
image emi basic_hes_gym_close = "sprites/emi/close/emi_basic_hes_gym_close.png"
image emi basic_happyblush_gym_close = "sprites/emi/close/emi_basic_happyblush_gym_close.png"
image emi basic_happy_gym_close = "sprites/emi/close/emi_basic_happy_gym_close.png"
image emi basic_grin_gym_close = "sprites/emi/close/emi_basic_grin_gym_close.png"
image emi basic_confused_gym_close = "sprites/emi/close/emi_basic_confused_gym_close.png"
image emi basic_closedsweat_gym_close = "sprites/emi/close/emi_basic_closedsweat_gym_close.png"
image emi basic_closedhappy_gym_close = "sprites/emi/close/emi_basic_closedhappy_gym_close.png"
image emi basic_closedgrin_gym_close = "sprites/emi/close/emi_basic_closedgrin_gym_close.png"
image emi basic_annoyed_gym_close = "sprites/emi/close/emi_basic_annoyed_gym_close.png"

# Meiko sprites

image meiko smile = "sprites/meiko/meiko_smile.png"
image meiko happy = "sprites/meiko/meiko_happy.png"
image meiko worry = "sprites/meiko/meiko_worry.png"
image meiko wink = "sprites/meiko/meiko_wink.png"
image meiko serious = "sprites/meiko/meiko_serious.png" 



# Shizune sprites

image shizune no_glasses = "sprites/shizu/shizu_adjust_noglasses.png"

image shizune cross_wut = "sprites/shizu/shizu_cross_wut.png"
image shizune cross_rage = "sprites/shizu/shizu_cross_rage.png"
image shizune cross_rageclosed = "sprites/shizu/shizu_cross_rageclosed.png"
image shizune cross_angry = "sprites/shizu/shizu_cross_angry.png"

image shizune behind_smile = "sprites/shizu/shizu_behind_smile.png"
image shizune behind_sad = "sprites/shizu/shizu_behind_sad.png"
image shizune behind_frustrated = "sprites/shizu/shizu_behind_frustrated.png"
image shizune behind_frown = "sprites/shizu/shizu_behind_frown.png"
image shizune behind_blank = "sprites/shizu/shizu_behind_blank.png"

image shizune basic_sparkle = "sprites/shizu/shizu_basic_sparkle.png"
image shizune basic_normal = "sprites/shizu/shizu_basic_normal.png"
image shizune basic_normal2 = "sprites/shizu/shizu_basic_normal2.png"
image shizune basic_happy = "sprites/shizu/shizu_basic_happy.png"
image shizune basic_frown = "sprites/shizu/shizu_basic_frown.png"
image shizune basic_angry = "sprites/shizu/shizu_basic_angry.png"

image shizune adjust_smug = "sprites/shizu/shizu_adjust_smug.png"
image shizune adjust_happy = "sprites/shizu/shizu_adjust_happy.png"
image shizune adjust_frown = "sprites/shizu/shizu_adjust_frown.png"
image shizune adjust_angry = "sprites/shizu/shizu_adjust_angry.png"
image shizune adjust_blush = "sprites/shizu/shizu_adjust_blush.png"



# Misha sprites

image misha hips_frown = "sprites/misha/misha_hips_frown.png"
image misha hips_grin = "sprites/misha/misha_hips_grin.png"
image misha hips_laugh = "sprites/misha/misha_hips_laugh.png"
image misha hips_smile = "sprites/misha/misha_hips_smile.png"

image misha cross_frown = "sprites/misha/misha_cross_frown.png"
image misha cross_grin = "sprites/misha/misha_cross_grin.png"
image misha cross_laugh = "sprites/misha/misha_cross_laugh.png"
image misha cross_smile = "sprites/misha/misha_cross_smile.png"

image misha perky_smile = "sprites/misha/misha_perky_smile.png"
image misha perky_sad = "sprites/misha/misha_perky_sad.png"
image misha perky_confused = "sprites/misha/misha_perky_confused.png"

image misha sign_confused = "sprites/misha/misha_sign_confused.png"
image misha sign_smile = "sprites/misha/misha_sign_smile.png"
image misha sign_sad = "sprites/misha/misha_sign_sad.png"
